# Generated by Django 6.1 on 2026-08-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=100)),
                ('lap_number', models.IntegerField()),
                ('audio_file', models.FileField(upload_to='race_audio/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('mood_confidence', models.FloatField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
