# Generated by Django 6.1 on 2026-08-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesession',
            name='lap_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
