# Generated by Django 6.1 on 2026-08-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_racesession_lap_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesession',
            name='lap_time',
        ),
    ]
